include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    sort_pub_dependencies: false

analyzer:
  exclude: [build/**, lib/**.frezzed.dart, lib/**.g.dart, lib/**.config.dart, lib/firebase/firebase_options.dart]